from kicad_evaltor.checks import (
    Check,
    CheckCategory,
    CheckParams,
    CheckRegistry,
    CheckResult,
    ComponentExistsCheck,
    ComponentPropertyCheck,
    ComponentsConnectedCheck,
    ComponentValueCheck,
    ConsistencyCheck,
    DRCRunCheck,
    ERCRunCheck,
    FootprintAssignedCheck,
    FootprintExistsCheck,
    FootprintOverlapCheck,
    PowerPourCheck,
    SymbolInLibraryCheck,
    SymbolSymbolOverlapCheck,
    TestStatus,
    TextOffSheetCheck,
    TextSymbolOverlapCheck,
    TextTextOverlapCheck,
    TextWireOverlapCheck,
    TraceLengthCheck,
    TraceWidthCheck,
    register,
)
from kicad_evaltor.core import DesignContext, TestReport, TestRunner
from kicad_evaltor.models import Component, Net, Pin, Track
from kicad_evaltor.utils import (
    SubprocessResult,
    filter_violations_by_severity,
    from_mils,
    parse_drc_report,
    parse_erc_report,
    run_kicad_cli,
    to_mils,
    to_mm,
    to_nm,
)

__version__ = "0.1.0"

__all__ = [
    "Check",
    "CheckCategory",
    "CheckParams",
    "CheckRegistry",
    "CheckResult",
    "Component",
    "ComponentExistsCheck",
    "ComponentPropertyCheck",
    "ComponentValueCheck",
    "ComponentsConnectedCheck",
    "ConsistencyCheck",
    "DRCRunCheck",
    "DesignContext",
    "ERCRunCheck",
    "FootprintAssignedCheck",
    "FootprintExistsCheck",
    "FootprintOverlapCheck",
    "Net",
    "Pin",
    "PowerPourCheck",
    "SubprocessResult",
    "SymbolInLibraryCheck",
    "SymbolSymbolOverlapCheck",
    "TestReport",
    "TestRunner",
    "TestStatus",
    "TextOffSheetCheck",
    "TextSymbolOverlapCheck",
    "TextTextOverlapCheck",
    "TextWireOverlapCheck",
    "TraceLengthCheck",
    "TraceWidthCheck",
    "Track",
    "filter_violations_by_severity",
    "from_mils",
    "parse_drc_report",
    "parse_erc_report",
    "register",
    "run_kicad_cli",
    "to_mils",
    "to_mm",
    "to_nm",
]
